version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://urlshortener:password@postgres:5432/urlshortener_db
      - DATABASE_SSL=false
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urlshortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
