version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_URL=postgresql://user:password@db:5432/mydatabase
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    depends_on:
      - db
    command: >
      sh -c "
        npm run db:setup &&
        node server.js
      "
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: