version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    command: npm start
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/urlshortener
      BASE_URL: http://localhost:3000
    ports:
      - '3000:3000'

volumes:
  db_data:
